name: 'Release'

on:
  pull_request:
    branches:
      - release
      - daily
    types: [closed]

jobs:
  build-and-release:
    name: "Creating Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm i
      - name: Semantic Release
      - uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}